### PR TITLE
Resolve showing error in PHPStorm

### PR DESCRIPTION
**Pull request by xgenvn**
This is an re-submited PR. Added vars declarations and comments for not being reported as error under PHPStorm.

### CODE REVIEW

**Comment by Rayne** [comment]
Please resubmit this PR to [fatfree-core](https://github.com/bcosca/fatfree-core), the development repository for the library.

**Comment by xgenvn** [comment]
@Rayne Can you help me explain how to do this the easiest way? I haven't do resubmiting to other repo before.
Thank you.

**Comment by ikkez** [comment]
Nevermind. I want to ask the question if we really want to start fixing thinks for a specific IDE? Don't get me wrong, PhpStorm is great and JetBrains is a F3 sponsor as well. But this commit doesn't bring that much value. Furthermore it touches code that actually works well and doesn't need a change, like the `$key="";` line https://github.com/bcosca/fatfree/pull/865/files#diff-3267a2e9d16decfe96b1574917f584dbR691 that variable is properly defined 3 lines below. If the IDE isn't able to recognize that simple thing, it's not our department (IMO). And if someone really need to work on the format method, you need to grab the `localeconv()` documentation anyways to see what is going on. So.. what's the rest of you is thinking about that?

**Comment by bcosca** [comment]
I totally agree with @ikkez here. Even [phpdepend](http://pdepend.org/documentation/getting-started.html), the premier tool in PHP software metrics, is simply too dumb to recognize the result of an `extract()`. It isn't a shortcoming of the framework, but the tool used.

**Comment by xgenvn** [comment]
Well, firstly I don't really want to make this PR, since it's like what you said, it's a side PR.
Secondly, the source code itself has some tiny problems here. 
I know this is a small framework and you want to cut down the size. My insight is ***$key = ""*** is supposed to be the same with ***$output = array()*** (the line above). However, it's better to be "$key = substr() ... ".
And for the using of extract() or other functions that looks like a magical wand, it's fine though. But when I start looking into the source, you'll ask yourself where a whole bunch of extracted vars are coming from.
Finally, maybe this should not be merged into main stream, instead of that, I think it can be a small patch for who working with PHPStorm atm. And perhaps I just can use this as a refer:
http://stackoverflow.com/questions/11129857/how-to-exclude-files-folders-from-code-inspection-in-phpstorm

**Pull request closed without merging**
