### PR TITLE
add var declaration for not showing error under phpstorm

### PR DESCRIPTION
**Pull request by xgenvn**
Add some params declaration for not being auto-marked as errors under PhpStorm.

### CODE REVIEW

**Comment by Rayne** [comment]
Please fix this pull request as it changes the programming style of the whole file (spaces instead of tabs, `{` brackets on new lines, spaces in conditions and so on).

**Comment by xgenvn** [comment]
@KOTRET I'm using PhpStorm to develop, sometimes I have to look into the source for better understanding, and It shows errors of undeclared variables (being unpack from an array param, or magic function). Not much expectation, but with those comments, we also know which vars are being unpacked, and somewhere else should put serious initiation for magic function.
If you're not using that IDE, it's just fine. For me and others who are using it, the errors are frustrated.

**Comment by Rayne** [comment]
These undefined variable warnings are annoying and your PR looks like it would improve the documentation and fix the warnings for PhpStorm (and compatible IDEs). If you are still interested in providing this patch, please create a new PR without changing and then reverting 3000+ lines.

**Comment by xgenvn** [comment]
@Rayne Okay, I'll submit another pull request.

**Pull request closed without merging**
