### PR TITLE
Patch for Unsafe MIME Type detection

### PR DESCRIPTION
**Pull request by Jiab77**
Related to opened issue: https://github.com/bcosca/fatfree/issues/1138.

This should be tested also on Windows before it should be validated as I can't test it on this system actually, Linux only for now.

### CODE REVIEW

**Comment by Jiab77** [comment]
Test code used:

```php
$f3->route('GET /mime-test',
	function() {
		$file = '/path/to/file.mkv';
		$file2 = 'https://url-to-image-file';
		$web = \Web::instance();
		$mime = $web->mime($file);
		$mime2 = $web->mime($file2);
		echo '<p><code>MIME</code> given for file [' . basename($file) . ']: ' . $mime . '</p>';
		echo '<p><code>MIME</code> given for file [' . $file2 . ']: ' . $mime2 . '</p>';
	}
);
```
Returned:

```
MIME given for file [file.mkv]: video/x-matroska

MIME given for file [https://url-to-image-file]: image/jpeg
```

**Comment by KOTRET** [comment]
The current implementation is very basic and neither requires to open and read the file (what could have bad sideeffecs and security issues and at least you notify the host that you accessed the file) nor a mime-magic-configuration.
NB: please make the pull request against [fatfree-core](https://github.com/bcosca/fatfree-core)

**Comment by Jiab77** [comment]
@KOTRET Sorry but I don't following you... What do you want me to do? Did you looked at my pull request before saying it require the user to have the file on local?? I wrote both conditions + fallback to make sure images MIME types are correctly detected, so I don't understand at all your comment.

**Comment by Jiab77** [comment]
Will close this pull request and recreate one over fatfree-core.

**Pull request closed without merging**
