### PR TITLE
Migrate to composer

### PR DESCRIPTION
**Pull request by sgpinkus**
Bite the bullet migrate F3 to composer. With this change, F3 now requires fatfree-core via composer. Submodule is gone. Essentially, the bcosca/fatfree repo now serves as a sample application, documentation, and container for tests all in one. Bit weird but works well. Refs #761.

Note, at current there is a bug in the fatfree-core composer.json that stops it autoloading classes. PRd (/bcosca/fatfree-core#31) fix. This works with that.

### CODE REVIEW

**Comment by KOTRET** [comment]
:-1: F3 is a seperate Project. Composer should be usable, but its up to @bcosca whether to use it or not. As Fat Free Framework comes with no dependencies - why add composer to it? it makes no sense. The Name of this framework is selfexplaining.

**Comment by sam-at-github** [comment]
> :-1: F3 is a seperate Project. Composer should be usable, but its up to @bcosca whether to use it or not. As Fat Free Framework comes with no dependencies - why add composer to it? it makes no sense. The Name of this framework is selfexplaining.

/bcosca/fatfree-core is a separate project. The only difference is now that the particular application of /bcosca/fatfree-core that is /bcoscafatfree, pulls in its dependency on /bcosca/fatfree-core via composer instead of a git submodule. /bcosca/fatfree-core can still be used with or without composer. I think this change makes things much clearer.

**Comment by ghazispeakserve** [comment]
It is not about adding more dependencies to F3, it is about enabling composer for it. F3 is used in non-fat-free projects ( large scale ) in which we need to add libraries, here composer comes to help. @bcosca is the repo owner of course and he should be aware of what his framework became, a lot of users that enables composer by their own and facing problems. It is more about unifying forces to get what is needed not about selfishness.

**Comment by sam-at-github** [comment]
One thing to note about this is that this PR is to dev, and the composer file currently requires fatfree-core:master. There is no dev branch in fatfree-core. In future may want to add a dev branch to fatfree-core. For now since its on dev I think its OK.

**Comment by boussou** [comment]
I agree that FafFree should work of the shelf, with no dependancies.
I must warn everyone that adding composer in  a project has a big impact on performance.
I can provide figures if you want.

**Comment by sam-at-github** [comment]
> I must warn everyone that adding composer in a project has a big impact on performance.
I can provide figures if you want. 

Yes please. I don't understand what your talking about.

**Comment by boussou** [comment]
I performed last year a benchmark (called "the bloat test") of various frameworks (among them Slim, Laravel & F3). 
> The test was: a simple controller returning a JSON object containing random values (string & ints) - then running **ab -n 1000 -c 5 url** on each on physical server (4 cores) & PHP 5.3 + APC

the results: 
- F3 base	 **228 r/s**
- F3 + composer	**172 r/s**
- Slim+ composer	153 r/s
- Slim Starter	77 r/s

**Conclusion: it seems that when you add composer to your project, you immediately loose 40% of performance**

FYI, I tried with composer "optimise" option, it helps a bit but to me it is not significant.
It appears that composer sucks at classloading, PSR 1 or 4 it is the same.
 
FYI too, Laravel & Symfony are pathetic (22 r/s on same configuration)

FYI, last, PHP 5.4+built in cache gives the same figures ( I followed this guideline http://fideloper.com/install-zend-opcache)

**Comment by sam-at-github** [comment]
@bcosca. Ok so firstly it does not seem unreasonable that the composer autoloader is slightly slower. It supports PSR-1|4, and a couple of other methods of autoloading.  Secondly I don't agree with your stated conclusion for two reasons. You lose X amount of performance in *loading*. Your test was designed to expose the loading phase by having a very trivial work load. I ran a similar test but on the fatfree app home page, and saw negligible difference. Also X=1-(172)/228 = 25% not 40%. And finally saw what about it? We are talking about an application of fatfree . You don't have to use composer, you just download fatfree-core and  continue using it APU.

**Comment by boussou** [comment]
Agreed mostly. 
the 40% value was taken from another row in my result excel sheet (oops)

I think that fatfree should be compatible with composer, but not composer based for autoloading by default.

Regarding performances, we all know that it direclty depends on the number of files loaded before sending response. 
- Fatfree (without composer): 18 files
- slim: 18
- Laravel: 127 files

About your test on the fatfree app home page, please don't forget about caching, maybe you were testing the performance of the caching system. Especially when content doesn't change, HTTP routing was made to optimize traffic (etags etc).

My point was, if a design is slow by nature, it cannot be fast later on ;-)
(I know, people always end up saying it doesn't matter because there's a front cache.)

**Comment by ghazispeakserve** [comment]
Yes for composer integration, no for using composer autoload with F3. F3 should load his libraries using its autoload function. I agree that I had to create a shell script that re-organises the dependencies folders...!!

**Comment by ikkez** [comment]
here is a demo setup how to use fatfree + composer, with composer autoloader for dependencies and F3 autoloader for own app files.
https://github.com/F3Community/fatfree-composer-app

**Comment by ptdev** [comment]
@ikkez great! I think the "getting started" section of the readme should have these (or similar) instructions besides the current require method to facilitate any newcomers to F3. As it is now, it has no mention of composer anywhere. Also, ideally it would have instructions on how to use composer for both the latest stable and the bleeding edge as I believe most of us use that instead of stable. Just a suggestion since nowadays pretty much every php lib/project have composer instructions.

**Comment by stehlo** [comment]
@ptdev Well, you should consider to do it yourself, or alternatively pay for it to be done for you.

**Comment by stehlo** [comment]
@boussou @sam-at-github @bcosca @ptdev @GhaziTriki @KOTRET @ikkez  Most people don't bother about performance these days because they don't understand what performance is and what it is good for. (They actually don't build applications that require performance. Also they mostly don't have competence for such a development. Obviously I am not talking just about using "popular" web servers, databases, PHP apps and PHP itself here, as they are not enough for achieving "performance".)

**Comment by hannahwarmbier** [comment]
+1 for composer documentation.

**Pull request closed without merging**
