### PR TITLE
SQL\Mapper Array args expanding

### PR DESCRIPTION
**Pull request by Okspen**
Here is a feature to SQL\Mapper. If query param is array, for example
```
$events = (new EventInfo())->find([
    'id IN :id',
    'id' => [266, 265, 264]
], [
    'limit' => 10
]);
```

It expands :id to list and query works. In this case `:id` is expanded to `(:id0,:id1,:id2)`. And args are converted respectively.

### CODE REVIEW

**Comment by xfra35** [comment]
Nice :)

Didn't you mean `id IN (:id)` rather than `id = :id`?

I think the procedure shouldn't return parenthesis. Thus it would be compatible with all sorts of syntaxes involving arrays, such as PostgreSQL or Oracle array types.

Would have been nice to have such an expanding feature working with question mark placeholders, but that's a little bit trickier.

**Comment by xfra35** [comment]
Actually, there's an issue: the framework already processes array arguments, for another purpose (user-specified data type):
https://github.com/bcosca/fatfree-core/blob/4d711d78cdc476d17ff638e101eb226d5ee48c23/db/sql.php#L206

**Comment by Okspen** [comment]
@xfra35 Thanks for review

You're right about `id IN :id`.

Regarding parenthesis. I found that oracle and postgres use parenthesis for this situation:
http://www.postgresqltutorial.com/postgresql-in/
https://docs.oracle.com/cd/B19306_01/server.102/b14200/conditions013.htm

Am I correct or am I missing something?

`?` placeholders - good idea. I'll add it.

**Comment by Okspen** [comment]
@ikkez I look on `WHERE` condition too. Can you please explain why would you need to parse the query and transform named placeholders to positional? The only reason I can think of is avoiding duplicated named placeholders in case when user would name them similar way :-)

**Comment by ikkez** [comment]
As far as I can see in your code, you are not looking at the `WHERE` condition, you determine this array expand feature based on the fact that `$args[$key]` is an array and not if it is used in an `IN` comparator. Well we could do it this way sure, but it collides with another feature here.
Yes I converted them to be able to map multiple used `:foo` named placeholders accordingly, or mix the usage as well. And I parse the query this way because there's also some more things goning one, i.e. NULL parameter helper, prefixing fields with related table names and qouting fields automatically. But that's all too much to be related to this issue I guess.

**Comment by ikkez** [comment]
hey @Okspen, yes the cortex stuff much too much, I didn't even thought about taking that as a code alternative here.

The SQL DB engine and its mapper has a feature to set a custom data type to your bind value. That already uses an array too:

```php
$mapper = new \DB\SQL\Mapper($f3->DB, 'file_db');
$mapper->name = "South Park";
$mapper->file = [fopen('ui/images/south-park.jpg', 'rb'), \PDO::PARAM_LOB];
$mapper->save();

$file = file_get_contents("ui/images/south-park.jpg");
$f3->DB->exec('insert into file_db VALUES(:name, CONVERT( VARBINARY(MAX),:file ))',
	array(':name'=>'South Park',':file'=>array($file,\PDO::PARAM_LOB)));
```

**Comment by Okspen** [comment]
@ikkez Thanks for the idea of taking array keys as basics for named parameters search. This is simpler. I rewrote the code. 

However, this use case, which was also pointed by @xfra35 breaks my pretty story :-) The workaround looks pretty messy to me at the moment.

**Pull request closed without merging**
