### PR TITLE
Update base.php

### PR DESCRIPTION
**Pull request by webbird**
Fix for "Fatal error: Directive ... deprecated" error messages

### CODE REVIEW

**Comment by webbird** [comment]
Description: In some environments, one my encounter "Fatal error: Directive ... deprecated" error messages using F3. I found the solution I've implemented here:
https://groups.google.com/forum/#!msg/f3-framework/G0m4DeFxTh4/OqPi2l5p6MAJ

Works perfectly for me.

**Comment by webbird** [comment]
There are several postings concerning this problem. If the people don't find a solution very fast, they may drop using F3. So why not implementing this workaround? It doesn't hurt, does it?

**Comment by KOTRET** [comment]
> There are several postings concerning this problem. If the people don't find a solution very fast, they may drop using F3. So why not implementing this workaround? It doesn't hurt, does it?

Of course _imho_ it hurts when talking about code quality! It simply does not "punish" you for using old deprecated code.
A framework should not actively feed the lazyness of some developers, but instead provide suitable workaround / solution for the rare case where old / deprecated code must be supported.
A proper workaround is given. If you as developer are not willing to read something about the framework, then its your choice, but the framework is not supposed to be foolproof in all cases.

**Comment by xfra35** [comment]
This issue has already been treated: https://github.com/bcosca/fatfree-core/pull/125.

Just call `error_reporting(0)` before loading `base.php`.

**Comment by webbird** [comment]
No need to be unpleasant.

**Pull request closed without merging**
