### PR TITLE
Fix missing newlines after template expansion

### PR DESCRIPTION
**Pull request by sorbits**
Before this commit the following code:

```
$template = "{{ @foo }}\nbar\n";
var_dump(Preview::instance()->resolve($template, array('foo' => 'bar')));
```

Would output:

```
string(7) "barbar\n"
```

This is because the template expander will replace `{{ … }}` with `<?php … ?>` and when such tags are followed by a newline, the PHP preprocessor omits it.

Since the template engine is mentioned as useful for generating emails, the newline stripping behavior is undesired and should not be inherited from PHP.

### CODE REVIEW

**Comment by sorbits** [comment]
Release 3.4.0 re-introduce the old behavior.

Since 3.4.0 is just done as one major commit, it’s not easy to see where exactly this broke or if the change was intentional.

**Comment by xfra35** [comment]
It looks like it broke [here](https://github.com/bcosca/fatfree/commit/ed8221d37d578412550c9d8493bf529188de7c42) so it doesn't look intentional.

**Comment by ikkez** [comment]
hmm, that fix for Cookie expiration is not related to this template fix. I guess bong inadvertently worked on an old, not pulled, version of the base file. It should be merged once more.

**Comment by sorbits** [comment]
Thanks for tracking down the problematic commit @xfra35.

Looking at the cookie fix, it looks like the review done was superficial. I have submitted a bogus commit myself (#634) which was also merged (well, it was a good commit but I accidentally updated the branch I had asked to be merged, before it got merged).

These two incidents makes me a little worried that code review is not very thorough. Hopefully I have just been unlucky — I don’t follow this project closely, so I don’t have an impression of how things are run day-to-day, just these few unfortunate incidents, but then when I go and try to audit the project, I get worried, because it seems keeping a good audit trail is not a priority, which made me file issue #761.

**Pull request merged**
