### PR TITLE
Fix SQL Error

### PR DESCRIPTION
**Pull request by jserle**
PDOStatement::fetchall throws error if called after a procedure that returns nothing. [The same problem](http://www.phing.info/trac/ticket/260) has been encountered in other frameworks.

### CODE REVIEW

**Comment by ikkez** [comment]
There are also cases where CALL or EXEC indeed return something (like `EXEC SP_HELPDB` returns the list of available databases). So, maybe there`s another fix.

**Comment by jserle** [comment]
That's a fair point.  Before opening this PR, I was catching the error using some like:
```php
if ($msg === 'SQLSTATE[HY000]: General error'){
    // skip error
} else {
    // handle error
}
```
But, it feels like a hack.  Maybe there are cases where it's a legit error that should be handled.
I was hard-pressed for an alternate solution, I don't know if there's an easy, cross-platform way to introspect the procedure.  Also, procs can internally call other procs.

**Comment by jserle** [comment]
I'm thinking maybe to partially roll back this commit, and allow EXEC to remain in the pattern, but keep CALL out.  Based on articles like [http://stackoverflow.com/questions/2680745/differences-between-procedure-and-function-and-routine](this), CALL would not be returning values unless output variables are being used.  @ikkez  - thoughts?

**Comment by ikkez** [comment]
fixed

**Pull request closed without merging**
