### PR TITLE
Replacing PSR-4 autoloading with a standard file map

### PR DESCRIPTION
**Pull request by xmeltrut**
PSR-4 autoloading will not work because of the case difference (file is base but class is Base). This replaces it with a standard file map to include base.php with the Composer autoload.

### CODE REVIEW

**Comment by francisdesjardins** [comment]
Hi,

Been rechecking that issue and I have finally found the culprit, which could be either in F3 or PHPUnit.

So here is the code in F3

```php
if (PHP_SAPI=='cli') {
	// Emulate HTTP request
	if (isset($_SERVER['argc']) && $_SERVER['argc']<2) {
		$_SERVER['argc']++;
		$_SERVER['argv'][1]='/';
	}
	$_SERVER['REQUEST_METHOD']='GET';
	$_SERVER['REQUEST_URI']=$_SERVER['argv'][1];
}
```

And the one in PHPUnit

```php
public static function main($exit = true)
{
	$command = new static;

	return $command->run($_SERVER['argv'], $exit);
}
```

The use of ```$_SERVER['argv'][1]``` in both code causes the PHPUnit problem. When ```Base::instance()``` get called in ```base.php``` it initialize ````$_SERVER['argv'][1]``` value to ```/``` and PHPUnit is using that to load the test suite.

Any suggestions ? I am not pointing F3 nor PHPUnit about that conflict.

**Comment by bcosca** [comment]
Since you're running the framework in CLI mode, there's really nothing we can do about it because the framework itself has a specific syntax and order of arguments when running from the command line. Altering this behavior will BREAK backward-compatibility, and that's something we don't intend to do.

**Comment by francisdesjardins** [comment]
That makes sense! Thank you for your time.

**Comment by bcosca** [comment]
That explains the misunderstanding. All the time I thought you were running it as a Web app, which doesn't connect the dots with the autoloader.

**Pull request merged**
