### PR TITLE
Replace index.php rewrite rule with mod_dir FallbackResource setting

### PR DESCRIPTION
**Pull request by Ayesh**
My first PR to this project! Thank you very much for the awesome work an your effort in bringing a truly fat free framework to PHP!

---
The default `.htaccess` file we ship with F3 uses a rewrite to map all requests to the base `index.php` file. While it is still working, the[ `FallbackResource`](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#fallbackresource) setting can be used to offer the same feature, without additional overhead caused by a rewrite rule. 

Quoting from the documentation linked above:

> In earlier versions of httpd, this effect typically required mod_rewrite, and the use of the -f and -d tests for file and directory existence. This now requires only one line of configuration.

This PR replaces that rewrite with the new setting. We still have to keep the other 2 rewrite rules, but we at least remove one rewrite rule this time. `dir` module is enabled by default.

Thank you!

### CODE REVIEW

**Comment by xfra35** [comment]
Awesome 👍 I didn't know that one.

**Comment by KOTRET** [comment]
While `mod_rewrite` offers more fine-grained control, this does the job in most cases.
That should additionally be noted in the docs, also this requires `mod_dir` (which should be switched on by default, so no problem) and Apache `2.2.16`++

**Comment by Ayesh** [comment]
Thanks for the information, @KOTRET. 
The additional requirement of `mod_dir` can be troublesome I agree. I can work on an additional PR to the docs repo if this PR is approved, mentioning that `mod_dir` is required in addition to `mod_rewrite`. 

Thanks.

**Comment by xfra35** [comment]
After trying out the `FallbackResource`, I found two drawbacks:

1) When running an app in a subfolder, the directive throws a 500 error if the requested URI contains a directory. E.g:

* `http://localhost/my-app/` => OK (application root)
* `http://localhost/my-app/foo` => OK
* `http://localhost/my-app/foo/bar` => error 500

This is because in the latter case, Apache is looking for `/my-app/foo/bar/index.php` instead of `/my-app/foo/index.php`.

The solution is to hardcode the subfolder in the .htaccess:
```
FallbackResource /my-app/index.php
```
This is similar to defining `RewriteBase`, the only difference being that `RewriteBase` can be skipped in most cases.

2) There's currently a [bug](https://bz.apache.org/bugzilla/show_bug.cgi?id=52403) that skips the directive when the requested URI ends with `.php` and is located at the application root:

* `http://localhost/my-app/foo.php` => error 404
* `http://localhost/my-app/foo/bar.php` => OK

**Comment by ikkez** [comment]
> There's currently a bug that
And "currently" means that is was reported back in 2011 and not being fixed by now, so I doubt that `FallbackResource` will ever cover all edge cases you've found. Thanks for investigation @xfra35.

**Comment by xfra35** [comment]
`FallbackResource` is an excellent alternative to `mod_rewrite` providing we are aware of the two pitfalls described above.

I wouldn't change the repository default `.htaccess` though, as it won't let us drop `mod_rewrite` completely (because of the `HTTP_AUTHORIZATION` variable) and mixing the two directives will just confuse the newcomers (especially when running an app in a subfolder).

Anyway we can add a mention about `FallbackResource` in the docs.

Do you agree?

**Comment by Ayesh** [comment]
You are right we aren't getting rid of the mod_rewrite requirement just yet. But thanks, a reference in docs sounds great!

**Comment by xfra35** [comment]
Ok. Done here: https://github.com/F3Community/F3com-data/commit/86eebbbdc5d23b4d00f80e0c74059833ff79ca9d

**Comment by Ayesh** [comment]
Awesome! Thank you so much!

**Pull request closed without merging**
