### PR TITLE
Update base.php

### PR DESCRIPTION
**Pull request by stickypages**
I added an option for the X-XSS protection. The reason is, some times you need to setup a CORS server. 
Implemented it into the config file to make any adjustments. Might not be super elegant...

### CODE REVIEW

**Comment by bcosca** [comment]
Quite a circuitous algorithm that always ends up with:

```
header('X-XSS-Protection: 1; mode=block');
```

What gives?

**Comment by stickypages** [comment]
Basically giving options...

*Config Options*
HEADERS['X-XSS-Protection'] = TRUE    _(will render X-XSS-Protection)_
HEADERS['X-XSS-Protection'] = FALSE   _(will *NOT* render X-XSS-Protection)_
or NONE  _(will render X-XSS-Protection)_

You could just use
if($this->hive['HEADERS']['X-XSS-Protection'] != FALSE) {}

But I was just trying to cover all bases...

**Comment by bcosca** [comment]
`HEADERS` is not meant to be used for configuration.

**Comment by stickypages** [comment]
One last thought. 
Perhaps we could just disable it like, 

if($this->hive['X-XSS-Protection'] === FALSE) { 
    # No protection 
} else { 
    # Use protection
}

If you don't like that, any form of enable/disabling this feature would be nice. Not a fan of adjusting the base file, would prefer to set it up on an option like format. Possible?

**Comment by ikkez** [comment]
Why is `X-XSS-Protection` important for your CORS setup? Isn't it enough for you
 to set the `Access-Control-Allow-Origin: *` header?

**Comment by stickypages** [comment]
Yeah I set that, but seemed to cause me issues still. None-the-less, no big deal... Thanks for great work on the framework!

**Pull request closed without merging**
